### ISSUE TITLE
Upgrade from 3.14.0-04 to 3.15.2-01 fails

### ISSUE THREAD

**Issue by avazula** [sonatype-nexus-community/nexus-repository-apt#100]
* **What are you trying to do?**
Update my Nexus repository from 3.14.0 to 3.15.2

* **What feature or behavior is this required for?**
Basically followed [your documentation](https://support.sonatype.com/hc/en-us/articles/115000350007) on how to upgrade from 3.X to 3.Y
- Downloaded the tar archive from your site, checked the SHA1, uploaded it onto the server and untar it in /opt
- Copied the configuration files and SSL certificates from the older version:
    `sudo cp /opt/nexus/etc/jetty/jetty-https.xml /opt/nexus-3.Y/etc/jetty/`
    `sudo cp -R /opt/nexus/etc/ssl/ /opt/nexus-3.Y/etc/`
    `sudo cp /opt/nexus/bin/nexus.vmoptions /opt/nexus-3.Y/bin/nexus.vmoptions`
- Stopped the service: 
    `sudo systemctl stop nexus.service`
- Updated the symbolic link:
    `sudo ln -sfn /opt/nexus-3.Y /opt/nexus`
- Restarted the service:
    `sudo systemctl start nexus.service`

The command above doesn't return any error message when the service starts, but when you check the status about a dozen of seconds after starting it, here's what I get:

    root@server-name:/opt/sonatype-work/nexus3/log# systemctl status nexus.service 
    * nexus.service - nexus service
    Loaded: loaded (/etc/systemd/system/nexus.service; enabled; vendor preset: enabled)
    Active: failed (Result: exit-code) since Thu 2019-03-07 10:25:04 CET; 24min ago
    Process: 4976 ExecStop=/opt/nexus/bin/nexus stop (code=exited, status=0/SUCCESS)
    Process: 4603 ExecStart=/opt/nexus/bin/nexus start (code=exited, status=0/SUCCESS)
    Main PID: 4765 (code=exited, status=255)

    Mar 07 10:24:49 adahra systemd[1]: Starting nexus service...
    Mar 07 10:24:49 adahra systemd[1]: Started nexus service.
    Mar 07 10:25:04 adahra systemd[1]: nexus.service: Main process exited, code=exited, status=255/n/a
    Mar 07 10:25:04 adahra nexus[4976]: Shutting down nexus
    Mar 07 10:25:04 adahra nexus[4976]: nexus is not running.
    Mar 07 10:25:04 adahra systemd[1]: nexus.service: Unit entered failed state.
    Mar 07 10:25:04 adahra systemd[1]: nexus.service: Failed with result 'exit-code'.

* **How could we solve this issue? (Not knowing is okay!)**
I don't know! :)
* **Anything else?**
Ducks are nice.

**Comment by avazula** [comment]
Shoot, I'm realizing this repo is for the APT plugin only. I'm sorry for bothering you. Could someone please delete this issue?

**Comment by mpoindexter** [comment]
Closing per submitter request
