### ISSUE TITLE
Where is 1.0.10 release?

### ISSUE THREAD

**Issue by fengxuway** [sonatype-nexus-community/nexus-repository-apt#106]
* **What are you trying to do?**
I want to download release version 1.0.10, but not found in releases page.

* **What feature or behavior is this required for?**
The version 1.0.10 in this page: <https://github.com/sonatype-nexus-community/nexus-repository-apt/releases>

* **How could we solve this issue? (Not knowing is okay!)**
Okay.
* **Anything else?**
Have no.

**Comment by exabrial** [comment]
Looks like he forgot to push the tag :)

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
