### ISSUE TITLE
Update to 3.16.1

### ISSUE THREAD

**Issue by xihefeng** [sonatype-nexus-community/nexus-repository-apt#108]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
update the version to 3.16.1 
* **What feature or behavior is this required for?**
apt proxy
* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by stohrendorf** [comment]
Any news on this?

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
