### ISSUE TITLE
How to update the version

### ISSUE THREAD

**Issue by kadosh1000** [sonatype-nexus-community/nexus-repository-apt#109]
This is not an issue, but more looking for an update guide.
I am using version 3.14.0 of this docker image, I want to update to the latest version (3.15.2).

Can anyone provide me a simple guide how to do it without loosing all the artifacts already there?

Thansk

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
