### ISSUE TITLE
java.io.IOException: unknown object in stream: 35

### ISSUE THREAD

**Issue by FilipPlotnicki** [sonatype-nexus-community/nexus-repository-apt#12]
Hi!
While trying to send a deb package to nexus with
`curl -u username:password -X POST -H "Content-Type: multipart/form-data" --data-binary "@my_deb.deb" http://<hostname>:8085/repository/<name>/ -v`
I'm getting this error:
`
>   Trying <ip>...
> TCP_NODELAY set
> Connected to <hostname> (<ip>) port 8085 (#0)
> Server auth using Basic with user '<username>'
> POST /repository/ubuntu/ HTTP/1.1
> Host: <hostname>:8085
> Authorization: Basic b2RlcGxveW06OSEqcWFfdzUpRW4n
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: multipart/form-data
> Content-Length: 26185188
> Expect: 100-continue
< HTTP/1.1 100 Continue`
`
> We are completely uploaded and fine
> HTTP/1.1 500 java.io.IOException: unknown object in stream: 35
> Date: Thu, 17 Aug 2017 13:14:02 GMT
> Server: Nexus/3.4.0-02 (OSS)
> X-Frame-Options: SAMEORIGIN
> X-Content-Type-Options: nosniff
> Pragma: no-cache
> Cache-Control: post-check=0, pre-check=0
> Expires: 0
> Content-Type: text/html
> Content-Length: 2075
`

What can be the cause of this error?

**Comment by mpoindexter** [comment]
This looks like a problem coming out of BouncyCastle trying to read your public/private key to sign the repository.

Check the key and password you've uploaded in the hosted repo config screen.

**Comment by FilipPlotnicki** [comment]
OK, it turned out that the fault was on our server provider's side. We can safely close this issue. Sorry for the trouble.
