### ISSUE TITLE
Nexus 3.6.0

### ISSUE THREAD

**Issue by Hermain** [sonatype-nexus-community/nexus-repository-apt#15]
Is this plugin supposed to run on 3.6.0? 

I tried the "most permanent" instructions and failed (sorry I don't remember the error message shown in UI / logs). Now that I didn't find an alternative I would be happy if you could confirm that it is supposed to work with newer nexus repository versions to justify trying once again to install it.

**Comment by testuser7** [comment]
It's working. You just need to update nexus-plugin to version 3.6.0-02 in pom file.

**Comment by Hermain** [comment]
Thx got it to work :)
