### ISSUE TITLE
Posting multiple packages with the same version leads to download problems

### ISSUE THREAD

**Issue by Hermain** [sonatype-nexus-community/nexus-repository-apt#23]
First of all thank you for providing this great plugin.

I have allow redeploy as deployment policy, however when I redeploy (different package content with same version) I get the following error when downloading the package:

`E: Failed to fetch https://blinded/repository/deb-package-repository/pool/l/mypackage/mypackage_0.3.0-1_amd64.deb  Writing more data than expected (134274 > 133814)`

This is resolved by removing the package and uploading it again.

Does this plugin not support redeployment? Any idea what the issue could be? Reloading index didn't help

**Comment by mpoindexter** [comment]
To be honest I've never tested redeploying the same version (I think it's a terrible idea, so I always turn it off).  I'll try to take a look at this in the next couple of weeks, but no promises.

**Comment by mpoindexter** [comment]
Should be fixed by https://github.com/mpoindexter/nexus-repository-apt/commit/66cd1d2d31db9e2107fbe18b02b86a98772e622c
