### ISSUE TITLE
How to use the repository with apt-get

### ISSUE THREAD

**Issue by gerbsen** [sonatype-nexus-community/nexus-repository-apt#26]
Hey there,
First of all thanks for providing this feature! I've installed this now on our NEXUS and uploaded the first custom build deb file. But now, I don't really know how I would add the repository to apt. My repository URL is: https://nexus.example.com/repository/apt-hosted/

Any help is kindly appreciated,
Cheers Daniel

**Comment by DarthHater** [comment]
@gerbsen I'll see if I can generate some user facing docs, might take a few days. You are welcome to contribute too!

**Comment by fehmer** [comment]
@gerbsen 
add to /etc/apt/sources.list
`deb https://nexus.example.com/repository/apt-hosted xenial main`

replace xenial with your ubuntu version.

**Comment by gerbsen** [comment]
Here are my notes. You have to create a GPG key first and with that sign you created package.

- ## Installing an artifact
  It's a little bit more involved to get something out of the repository then into.

  1. Switch to super user: `su`
  2. Add the new repository to apt's list of repos: `echo "deb https://repository.domain.com/repository/REPO_NAME/ xenial main" >> /etc/apt/sources.list.d/your-custom.list: `
  3. Add the auth part I: `echo "machine repository.domain.com" >> /etc/apt/auth.conf`
  4. Add the auth part II: `echo "login $NEXUS_USERNAME" >> /etc/apt/auth.conf`
  5. Add the auth part III: `echo "password $NEXUS_PASSWORD" >> /etc/apt/auth.conf`
  6. Import the public key of the private key used for signing: `apt-key adv --keyserver keyserver.ubuntu.com --recv-keys YOUR_PUBLIC_KEY_ID`
  7. Update apt: `apt-get update`
  8. Install package: `apt-get install package`

  There might be an issue with access to the repository. 
  In case you get errors like: 
   - `E: Failed to fetch https://repository.domain.com/repository/REPO_NAME/dists/xenial/main/binary-amd64/Packages  403  Forbidden` you have to edit the NGINX config for the NEXUS site, since we only allow IP from a certain whitelist.
   - `E: The method driver /usr/lib/apt/methods/https could not be found. N: Is the package apt-transport-https installed?` you need to install `apt-get install apt-transport-https`

**Comment by DarthHater** [comment]
@gerbsen I'll start a branch/PR, maybe you can add to it?

**Comment by DarthHater** [comment]
@gerbsen if you'd like to collaborate on #28 let me know! I shelled out some stuff but I would love for you to add to it. We can get you all setup to collaborate on the repo if you are down.
