### ISSUE TITLE
Building 1.0.5 release produces jar files named 1.0.4

### ISSUE THREAD

**Issue by Sean-Brown** [sonatype-nexus-community/nexus-repository-apt#44]
- I downloaded the latest release from the "Releases" for this repo
- I ran `mvn` (after commenting out tests -- I don't have vagrant installed and the tests appeared to fail because it couldn't create a VM) and it produced jar files named `nexus-repository-apt-1.0.4.jar`
- I am now confused because the instructions (and release version) indicate that the files should be named `nexus-repository-apt-1.0.5.jar`

The instructions themselves are a little confusing to me:
- Why do we have to build the JAR ourselves? Why is this not distributed as the "Release"?
- After building the JAR file, why do we need to run a docker container?
- Are both the JAR file and docker container necessary? 
- What is the purpose of the docker container?

**Comment by Sean-Brown** [comment]
Got it to work by just cloning the repo and building the JAR (after skipping maven tests by adding the following to pom.xml:
```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.18.1</version>
        <configuration>
          <skipTests>true</skipTests>
        </configuration>
      </plugin>
```

This build did produce the correct build numbers on the JAR file, so I'm guessing that was a bug that was fixed post-release. 

I still don't understand why you don't just distribute the JAR as the release -- why make the end user go through the hassle of building it, when all that really matters is the JAR?

I think the instructions would be more clear too if it said something to the effect of "Build manually or Build with Docker" -- the way the doc is structured it makes it appear as if both steps are required, instead of it being "one or the other".

**Comment by ju2wheels** [comment]
The JAR files are tied to a specific Nexus version on build from what I understood from building it at this [line](https://github.com/sonatype-nexus-community/nexus-repository-apt/blob/master/pom.xml#L8). Setting that incorrectly leads to issues with it loading in Nexus. So distributing the JARs would only be useful if they build one for the Nexus version wanted or maintained builds for each Nexus version that the current version of the plugin supports.

The docker container is only for building the plugin in an isolated build environmen and creating a Nexus build you can then run in Docker that contains the plugin. You could build it locally on your own machine and then put it into a locally installed Nexus setup instead.

The JAR file is the only thing you need, its the artifact of the build process that you then put into your Nexus setup.

**Comment by mpoindexter** [comment]
Closing this out since should no longer be an issue in the latest code
