### ISSUE TITLE
apt-transport-* support for proxies

### ISSUE THREAD

**Issue by heini** [sonatype-nexus-community/nexus-repository-apt#56]
Don't know whether or not this is already supported, so I file it as a feature request here.

Some external package repositories use https (or even tor) via *apt-transport-https* or *apt-transport-tor* to serve their packages. Do proxy repositories have support for getting packages from such external repositories, i.o.w. could I setup a proxy repository that caches packages from `tor+http://vwakviie2ienjx6t.onion/debian` instead of `http://ftp.de.debian.org/debian`?

If not, could this be added, please?

**Comment by mpoindexter** [comment]
This would be a lot of work to implement given that we don't use APT, so we'd have to implement all those protocols ourselves.

I don't think that this would be a good fit for what's supported in base Nexus (seems like Nexus core is pretty strongly HTTP oriented), but could in theory be implemented.  I don't personally have any plan to implement such a thing, but PRs would be welcome.

**Comment by DarthHater** [comment]
This would take changes in Nexus Repository itself, as it uses Jetty to serve files, and HttpClient to do communication to remotes. I can't see it personally getting implemented any time soon, but filing an issue with the Nexus Repo project [in JIRA](https://issues.sonatype.org/projects/NEXUS/) would be a good first start.

**Comment by mpoindexter** [comment]
I'm going to close this as out of scope since I don't think anyone has interest in working on this and the scope of work is quite large.
