### ISSUE TITLE
Create version matrix

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-repository-apt#60]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
The current version list on the README is good, but I think it would likely be visually easier for people if we create a version matrix

* **What feature or behavior is this required for?**
Mainly just so people can visually scan a little bit better on what version works with what, etc...

Perhaps we can link to release tags, as well.

* **How could we solve this issue? (Not knowing is okay!)**
Have fun! Write some markdown! Trace down what versions of the apt plugin work with what version of Nexus Repo, etc...

* **Anything else?**

**Comment by mpoindexter** [comment]
Seems like this is now integrated into the readme as a nice matrix/table, so closing out
