### ISSUE TITLE
Create components for packages rather than just assets

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-repository-apt#61]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Currently I believe the apt plugin creates all new packages that are either proxied or uploaded as assets. In order to better leverage Nexus Repository features, anything that is basically an apt package should be created as a component, with an asset attached to it.

* **What feature or behavior is this required for?**
This will allow features such as Search, Tree View, etc... to function better for the apt plugin

* **How could we solve this issue? (Not knowing is okay!)**
There are a number of ways by which to approach this, what I would suggest is taking a look at how we do this in the R, Conan, etc... plugins, likely in the ProxyFacetImpl classes, etc... and adapting apt to do something similar

* **Anything else?**
This is likely a big undertaking, so buckle in :)

**Comment by mpoindexter** [comment]
I think the hardest part would be migrating any existing data that is stored...@DarthHater, any examples of ways to do that in other plugins?

**Comment by DarthHater** [comment]
You'd want to probably take a look at how npm does this:

https://github.com/sonatype/nexus-public/blob/master/plugins/nexus-repository-npm/src/main/java/org/sonatype/nexus/repository/npm/internal/ComponentDatabaseUpgrade_1_9.java

That's an example of performing an upgrade, and should get someone started.

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
