### ISSUE TITLE
When running under IIS, error message "Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)" appears

### ISSUE THREAD

**Issue by gschizas** [sonatype-nexus-community/nexus-repository-apt#65]
I've setup Nexus on an IIS and I installed nexus repository apt plugin.

I've successfully uploaded a couple of packages in it, but when I try doing `apt-get update` from a client, I get the following error:

`Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)`

After some research, it seems that the problem is that IIS (being on Windows) sends the `InRelease` file with CRLF instead of LF. If I manually (I'm using Fiddler as a proxy-in-the-middle) remove the CR characters from the output, `apt-get update` works perfectly (I've managed to install a couple of packages).

I'm not entirely sure if this is nexus-repository-apt related, or it's a problem from nexus itself. I've found [a reference to BytesPayload in AptHostedFacet](https://github.com/sonatype-nexus-community/nexus-repository-apt/blob/master/src/main/java/net/staticsnow/nexus/repository/apt/internal/hosted/AptHostedFacet.java#L202). I also found that [AptSigningFacet](https://github.com/sonatype-nexus-community/nexus-repository-apt/blob/master/src/main/java/net/staticsnow/nexus/repository/apt/internal/gpg/AptSigningFacet.java#L106) signs the file after stripping the CR characters. I hope those help.

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
