### ISSUE TITLE
Nexus fails with "Resource mvn:net.staticsnow/nexus-repository-apt/1.0.7 does not contain a manifest"

### ISSUE THREAD

**Issue by sagarkhushalani** [sonatype-nexus-community/nexus-repository-apt#71]
* **What are you trying to do?**
Use nexus-repository-apt with Nexus OSS version 3.12.0-01

* **What feature or behavior is this required for?**
Not a feature; I followed the instructions on getting the jar into Nexus. However, on startup,
Nexus throws an error, that states:

    "Resource mvn:net.staticsnow/nexus-repository-apt/1.0.7 does not contain a manifest"

* **How could we solve this issue? (Not knowing is okay!)**
Not sure, but I can post any information you need.

* **Anything else?**
Attached the related section of log here.
[errorlog.txt](https://github.com/sonatype-nexus-community/nexus-repository-apt/files/2224804/errorlog.txt)

**Comment by mpoindexter** [comment]
cannot reproduce this
