### ISSUE TITLE
Is it possible to have deb-src files in the registry?

### ISSUE THREAD

**Issue by zentavr** [sonatype-nexus-community/nexus-repository-apt#74]
* **What are you trying to do?**
I had build the package using something like this: `dpkg-buildpackage -rfakeroot -us -uc`. As the result I have the next:
```
drwxrwxr-x 22 dpkgbuilder dpkgbuilder     4096 Aug 15 03:33 cmpossl-1.1.1-pre9-dev
-rw-rw-r--  1 dpkgbuilder dpkgbuilder     1628 Aug 15 03:33 cmpossl_1.1.1-pre9-dev_amd64.changes
-rw-r--r--  1 dpkgbuilder dpkgbuilder  9894188 Aug 15 03:33 cmpossl_1.1.1-pre9-dev_amd64.deb
-rw-rw-r--  1 dpkgbuilder dpkgbuilder     5848 Aug 15 03:22 cmpossl_1.1.1-pre9-dev.debian.tar.xz
-rw-rw-r--  1 dpkgbuilder dpkgbuilder      860 Aug 15 03:22 cmpossl_1.1.1-pre9-dev.dsc
-rw-rw-r--  1 dpkgbuilder dpkgbuilder 59439926 Aug 14 01:19 cmpossl-1.1.1-pre9-dev.tar.bz2
lrwxrwxrwx  1 dpkgbuilder dpkgbuilder       30 Aug 14 02:00 cmpossl_1.1.1-pre9.orig.tar.bz2 -> cmpossl-1.1.1-pre9-dev.tar.bz2
```
I would like to have deb-src registry with my sources as well. I wonder if I can do that?
Saying, **dupload** wants only the *.changes* file in order to proceed (but it loads all these `.dsc`, `.tar.xz` and `tar.bz`, but APT plugin for Nexus 3 as I understood from the manual wants only the `.deb`).

* **What feature or behavior is this required for?**
I would like to have the sources with the `.deb`s as well.

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
