### ISSUE TITLE
Asset history limit 0

### ISSUE THREAD

**Issue by pk1057** [sonatype-nexus-community/nexus-repository-apt#75]
Nexus 3.13
nexus-repository-apt: 1.07

uploading a new/different package to my repository via UI or curl

When i upload a new .deb the metadata Package file only shows the last uploaded debian package.
Every older upload vanished from the list.
The repository was newly created.
After i changed the number of historic packages the repository was populated as expected.
So it seems that there is a issue with initialization of history limit in a new repository

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
