### ISSUE TITLE
Feature Request: Support apt (group) repos

### ISSUE THREAD

**Issue by arthurvanduynhoven** [sonatype-nexus-community/nexus-repository-apt#76]
It would be nice to have group repos with apt.

* **What are you trying to do?**
Specify a single apt group repository.

* **What feature or behavior is this required for?**
Virtual/Group APT repository

* **How could we solve this issue? (Not knowing is okay!)**
Implement group apt repositories

* **Anything else?**

**Comment by naugler** [comment]
duplicates #10 - "Group support"
