### ISSUE TITLE
Please tag the 1.0.7 version

### ISSUE THREAD

**Issue by HT43-bqxFqB** [sonatype-nexus-community/nexus-repository-apt#77]
Could someone tag the current state with version `1.0.7 ` as `1.0.7` in this repo. This would allow easier pinning instead of using the hashes of the last commit.

**Comment by DarthHater** [comment]
@mpoindexter any issue with me doing this?

**Comment by mpoindexter** [comment]
I'd go ahead and bump the version to 1.0.8 and tag that I guess, but no issues.

**Comment by DarthHater** [comment]
@HT43-bqxFqB take a gander at #79 , that is my PR to update the pom, etc.... cc @mpoindexter

**Comment by HT43-bqxFqB** [comment]
Looks good, thanks! I'll close this issue when the PR is merged 👍

**Comment by DarthHater** [comment]
Merged! Let me know if you run into any issues @HT43-bqxFqB

**Comment by DarthHater** [comment]
Going to close this!
