### ISSUE TITLE
Create the jar file

### ISSUE THREAD

**Issue by vandman** [sonatype-nexus-community/nexus-repository-apt#82]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I am not familiar with maven and java. Each time I try to build the jar file, i get an error:
`[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-environment) @ nexus-repository-apt ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-dependencies) @ nexus-repository-apt ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
Found Banned Dependency: org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.556 s
[INFO] Finished at: 2018-11-02T12:49:18+01:00
[INFO] Final Memory: 33M/186M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-dependencies) on project nexus-repository-apt: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`
* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
1_ update this git to the latest nexus release 3.14.0-04.
2_ Help us to correct the pom.xml file in order to be able to build the jar file, or find a solution to provide the jar file?
* **Anything else?**
I am under debian9 using the default maven:
`Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
`
redards
vandman

**Comment by DarthHater** [comment]
I'll take a gander at this right now

**Comment by DarthHater** [comment]
On master I am able to build fine. This project doesn't use the enforcer plugin to explicitly ban any dependencies that I am aware of.

As well, you are building the project using open-jdk, so that might be something to take a look at. In the future we will be supporting those builds, but for now we are still using the Oracle JDK for stuff. I am using the exact same version of Maven as you locally, so that's likely ruled out. 

As well, there is a branch with an update to 3.14, check #80 , it could use testing!

**Comment by vandman** [comment]
Hi,
Sorry for the late reply.
You are right, It work now.
Thanks.
Vandman
