### ISSUE TITLE
Api call

### ISSUE THREAD

**Issue by Fantomatic** [sonatype-nexus-community/nexus-repository-apt#83]
* **What are you trying to do?**
We are trying to automate  all the configuration through an ansible deployment. For that i only found the groovy api which allow me to create yum repository. We also try to extend this automated configuration to apt configuration. 
* **What feature or behavior is this required for?**
We were wondering if it was possible to add the API to create apt repository through a groovy function like createAptProxy and createAptHosted.

**Comment by bhamail** [comment]
APT is now part of Nexus Repository Manager. Version 3.17.0 includes the APT plugin by default.
If this is still an issue if using 3.17.0 or later please file an issue at https://issues.sonatype.org/.
Links to the new source code location are in the top level README.md
