### ISSUE TITLE
Support for OpenJDK

### ISSUE THREAD

**Issue by EmporioHanzo** [sonatype-nexus-community/nexus-repository-apt#87]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Build the artifact with OpenJDK 1.8 or 11 but only works with Oracle JDK
* **What feature or behavior is this required for?**
Due to new reglementations for Oracle JDK
* **How could we solve this issue? (Not knowing is okay!)**
resolve javafx dependencies in pom to build with openjdk
* **Anything else?**

**Comment by mpoindexter** [comment]
Not sure there's much that this plugin can do about this.  Most of the build is the base Nexus POM files, so I think mostly it would require changes in that.
