### ISSUE TITLE
Update to use Nexus Repo 3.15

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/nexus-repository-apt#91]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

Pretty easy, update the plugin to use Nexus Repo 3.15

* **What feature or behavior is this required for?**

Just uses the latest and greatest, and should resolve some vulnerable dependencies, as well

* **How could we solve this issue? (Not knowing is okay!)**

Update the pom, Dockerfile and README

* **Anything else?**

Have fun!

**Comment by stohrendorf** [comment]
Any progress/obstacles on this? I'd like to see this resolved sooner than later, without falling back to a "non-official" release by utilizing #90.

**Comment by mpoindexter** [comment]
Implemented
